### ISSUE TITLE
[Dev] Update Registration Page UI

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#164]
Update the login page UI as per the current Figma design

https://www.figma.com/file/B0M4LvASkmA1MCM1v2JFUa/Hotel-Management-System?type=design&node-id=0-1&mode=design&t=ar6HLm8JAueUpFjK-0

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/1f345b06-5261-404d-9457-2f92c8dd3505)

UI was updated to following.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/5f2490fe-b3f6-4b90-8d34-86e9d1cec9c9)

**Comment by iamarasekera** [comment]
Requested changes in the PR
https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/183

**Comment by Anjalika11** [comment]
Backend Coding  done. But the plan of the phone number is to be updated.
The project font size is encoded into a relative size.

**Comment by iamarasekera** [comment]
The button button size is different to the design as the design is is updated at the time of the release.
@Anjalika11 you were suppose to mention this as well. 

@rmapramodya   therefore please skip testing font, button size on the UI.
