### ISSUE TITLE
[Dev] Implement Filter Functionality on Explore Page

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#167]
Implement the filter functionality in the Explore Page

As a user 
I want to be able to 
filter rooms by  Room type, number of guests and type of beds available,
So that I can filter out the rooms that fit exactly my needs. 

Note : The sort by filter is not included in this task. 

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/1142c4f6-18e6-41dd-b5a6-035b415a1487)

Figma Design : https://www.figma.com/file/B0M4LvASkmA1MCM1v2JFUa/Hotel-Management-System?type=design&node-id=0-1&mode=design&t=gbvbw4gUViSgkW6q-0

**Comment by sinera2000** [comment]
The last filter feature "Sort by" not been implemented yet. Need a small discussion
