### ISSUE TITLE
[Suggestion] Incorrect Font Usage in some sections (Privacy Policy, Terms & Conditions, Contact now banner, Cookie)

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#184]
Description - The font, font size & font color are incorrect in some sections.

1.

Test steps -
1.Navigate to the Privacy policy page.
2.Verify that the Page is present correctly.

Title - "Privacy Policy"

Expected result -
Font Size - 62px

Actual result -
Font size - 60px

effectiveDate - "Effective Date: May 8, 2023"

Expected result - 
Font - Mulish
Font size - 20

Actual Result -
Font - inter
Font size -16

description - "This Privacy Policy outlines how SLC...,  "

Expected result -
Font - Mulish
Font size - 20

Actual Result -
Font - Inter
Font size -16

title - "1.Information We Collect , 2.Use of Information, 3.Data Retention and Security, 4.Disclosure of Information, 5.Your Rights, 6.International Data Transfers, 7. Contact Us"

Expected result - 
Font - Mulish
Font size - 18
Font Weight - 600

Actual resul - 
Font - Inter
Font size - 24
Font weight - 400

Content - "We may collect personal..., When you visit our website..., We use the collected information..., We may use your personal..., We may use your personal..., We take appropriate..., We may engage trusted..., We may disclose your personal..., You have certain rights regarding..., Your personal information..., If you have any questions... "

Expected result -
Font - Mulish

Actual Result -
Font - Inter

2.

Test steps -
1.Navigate to the Terms & Conditions  page.
2.Verify that the Page is present correctly.

Title - "Terms & Conditions"

Expected Result - 
Font size - 62px
Font Family - Lora
Align - Left

Actual Result -
Font size - 34px
Font family - Inter
Align - Center

efectivedate - "Effective Date:2024-04-01"

Expected Result -
Font family - Mulish
Font size - 20px
Font weight - Bold

Actual result -
Font family - Inter
Font size - 24px
Font weight - normal (400)

description - "These Terms and Conditions..."

Expected result -
Font family - Mulish
Font size - 16px

Actual result -
Font family - Inter
Font size - 24px

Subsections - "1. Acceptance of Terms, 2. Intellectual Property, 3. Limitations of Liability
, 4. User Responsibilities, 5. Termination, 6. Governing Law, 7. Contact Us"

Expected Result - 
Font family - Mulish
Font size - 18px
Font weight - Semi bold

Actual result - 
Font family - Inter
Font size - 34px
Font weight - normal

title - "1.1 Agreement to Terms, 2.1 Ownership, 2.2 User Content, 3.1 Disclaimer of Warranties, 3.2 Limitation of Liability, 4.1 Compliance with Laws, 4.2 Security"

Expected Results - 
font family - Mulish
font weight - medium

Actual results - 
font family - Inter
font weight - medium

Content - "By accessing our website..., We reserve the right to modify..., The content, design, logos..., Any content you submit..., Our website and services..., To the extent permitted by...,You agree to comply ..., You are responsible..., We reserve the right to ..., These Terms shall..., If you have any questions.."

Expected results -
font family - mulish

Actual result -
font family - inter

3.

Test steps -
1. Navigate to the home page
2. Verify that the Contact now Banner is present on the page

contactNowTitle - "Best travel and destinations"

Expected result -
font size - 64px
font weight - 800

Actual result -
font size - 80px
font weight - 700

contactNowDescription - "With travala you..."

Expected result - 
font size - 16px
font color - FFFFFF   64%

Actual result - 
font size - 24px
font color - FFFFFF 70%

contactNowCaption - "Our Destination"

Expected result - 
font size - 18px
font weight - 500

Actual result - 14px
font weight - 700

4. 

Test steps-
1. Navigate to the home homepage.
2. Verify that the Cookie Component is present on the bottom of the page.

cookieButtonCaption - "Accept"

Expected Result - 
Font - Mulish

Actual Result -
Font - Inter

cookieButtonCaptionReject - "Reject"

Expected Result -
Font - Mulish 
Font color - 1A242D

Actual Result -
Font - Inter
Font color - Black

**Comment by iamarasekera** [comment]
@BupendraDhyan @Chmx00 ensure these issues are fixed when you apply theme.

**Comment by BupendraDhyan** [comment]
This is updated in following PRs:

https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/501
https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/494
https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/469
