### ISSUE TITLE
[Bug] Missing Outline Around Reject Button in Cookie Section

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#187]
Description:
In the Figma design of the website's Cookie section, there is a outline around the "Reject" button, showing its visual importance. However, upon testing the developed version of the website, it was noticed that the outline around the "Reject" button is missing.

Test Steps:

1. Navigate to the Cookie section of the website.
2. Observe the design of the "Reject" button.
3. Compare the presence of a outline around the "Reject" button in the Figma design to the developed version of the website.

Expected Result:

In both the design and the actual website, there should be a clear Outline around the "Reject" button. This helps keep the look of the website consistent and makes it easier for users to understand and use.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/863c5fe7-2e5a-46b5-81c8-22d573179303)

Actual Result:
In the developed version of the website, the outline around the "Reject" button is missing, different from the Figma design. This difference might make the Cookie section look less attractive and could confuse users.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/81bc926e-8071-463d-a537-d12ef69ae824)

**Comment by Sanjeewa001** [comment]
BUG-fixed

**Comment by rmapramodya** [comment]
This is fixed, Verified in version 1.0.4
