### ISSUE TITLE
[Bug] Missing Close Icon in Cookie Section

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#188]
Description:
The Figma design of the website's Cookie section includes a close icon, likely intended to allow users to close the Cookie notification. However, upon testing the developed version of the website, it was discovered that the close icon is missing.

Test Steps:

1. Access the Cookie section of the website.
2. Look for the presence of a close icon within the Cookie notification.
3. Compare the existence of the close icon in the design to the developed version of the website.

Expected Result:
In alignment with the design, the developed version of the website should include a close icon within the Cookie notification, enabling users to dismiss the notification easily.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/3f7c665b-be76-492e-8c2f-aa9695a04863)

Actual Result:
The close icon is missing from the developed version of the website, This is different from what was supposed to happen. This missing icon might make it harder for users to deal with the Cookie notification properly.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/9e454268-a8db-46b9-80b0-68937ae733f1)

**Comment by iamarasekera** [comment]
@Sanjeewa001 when you click on X button the banner should be closed and the cookies should not be saved.

**Comment by Sanjeewa001** [comment]
bug fixed add close button

**Comment by rmapramodya** [comment]
This is fixed, Verified in version 1.0.4
