### ISSUE TITLE
[Bug] Incorrect Alignment of Cookie Icon in Cookie Section

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#189]
Description:
Within the design of the website's Cookie section, there is a cookie icon intended to symbolize cookie settings or preferences. However, upon testing the developed version of the website, it was noticed that the alignment of the cookie icon is incorrect.

Test Steps:

1. Visit the Cookie section of the website.
2. Locate the cookie icon and observe its alignment.
3. Compare the alignment of the cookie icon in the Figma design to the developed version of the website.

Expected Result:
The cookie icon in the developed version of the website should be aligned correctly, matching the Figma design  and ensuring a visually cohesive Cookie section.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/32e1d2fc-628c-47e4-b973-bb25e03b105d)

Actual Result:
In the developed version of the website, the cookie icon isn't align right like it was supposed to be. This difference might mess up how the Cookie section looks and how users see it.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/d3a71324-59ab-4282-b14c-c321b9e9c6a2)

**Comment by Sanjeewa001** [comment]
**_Bug Fixed_**
redesign cookie icon in banner align to the **figma**

**Comment by rmapramodya** [comment]
This is not  fixed, Verified in version 1.0.4

**Comment by iamarasekera** [comment]
PR https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/236 approved and merged.  Please check test the fix in 1.0.5 and move to done.

**Comment by rmapramodya** [comment]
This is fixed, Verified in version 1.0.5
