### ISSUE TITLE
[Bug] Incorrect Button Radius in Cookie Section

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#190]
Description:
During testing of the website's Cookie section, it was noticed that there's a difference in the button radius between the Figma design and the developed version. According to the Figma design, the radius for both the reject and accept buttons should be 8. However, upon testing the developed website, it was found that the radius for both buttons is set to 12 instead of the expected 8.

Test Steps:

1. Navigate to the Cookie section of the website.
2. Inspect the reject and accept buttons to determine their border radius.
3. Compare the observed border radius to the expected value of 8, as specified in the design.

Expected Result:
The reject and accept buttons in the Cookie section should have radius of 8 pixels, as shown in the design. This makes sure they look right and work well for users.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/5f813237-3027-4a34-89c5-36fe66dfffe8)

Actual Result:
When we looked at the finished website, we noticed that both the reject and accept buttons have border radius of 12 pixels instead of the 8 pixels we expected. This difference from what was planned might make the Cookie section look a bit off and not as nice for users.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/732688f5-233a-4e73-8129-c70b4af10f05)

**Comment by Sanjeewa001** [comment]
**_Bug Fixed_**
change the border radius into 8px

**Comment by rmapramodya** [comment]
This is fixed, Verified in version 1.0.4
