### ISSUE TITLE
[Design] Error Pages for HMS front end

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#200]
1. Research on different error pages 
2.  Design error pages for web, tab  and mobile for HMS frontend
3.  The design should be reusable.

**Comment by BupendraDhyan** [comment]
Error pages designed. (404 error and 500 error pages)


![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97863220/7c74ab07-579a-473d-add8-739891d6f31c)
![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97863220/734727f8-3be0-49b2-9fb2-ca54158eb66f)
