### ISSUE TITLE
[Dev] Develop Error Message Template

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#204]
1.  Create a reusable component for error messages

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/c568ea06-66fa-4952-b65f-e6d3a1445d85)

Figma : https://www.figma.com/file/B0M4LvASkmA1MCM1v2JFUa/Hotel-Management-System?type=design&node-id=1969-3306&mode=design&t=eWgDW9Z6QBDnQBtL-0

**Comment by iamarasekera** [comment]
This PR https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/245 is merged.

**Comment by Anjalika11** [comment]
Error Message Link - http://localhost:3001/error-message
