### ISSUE TITLE
[Design] Update Nav Bar to add Blog Option and Remove Login and Register

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#205]
Update the Nav Bar to reflect the following changes
 1. Add Blogs
 2. Remove Login
 3. Remove Register

The same update should be applied to mobile and tabs

All pages should be updated with the new nav bar.

**Comment by BupendraDhyan** [comment]
1. Blog option added to every page.
2. Login button removed.
3. Register button removed.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97863220/18d2a56b-1334-4ee1-a76d-5b4cccd2868c)
