### ISSUE TITLE
[Design] update the search component as per the old design in Figma

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#208]
Design should be like this

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/a2590d1d-4380-47d0-8d6a-54a9f453e0ff)

**Comment by BupendraDhyan** [comment]
Updated the search component.


![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97863220/7056a6ee-aa46-47b7-99d9-54355bd01aa6)
