### ISSUE TITLE
[Design] Re-design the Footer for mobile view

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#210]
Resign the footer with a modern design 

Existing design :

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/0890559e-39da-4117-b38e-5de130299c2a)

**Comment by BupendraDhyan** [comment]
Footer updated. [Task 31]


![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97863220/5c292fa3-7c3b-4dc2-87e9-c2adf650a543)
