### ISSUE TITLE
[Dev] Verify Data assignment in Chekout Page

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#223]
All data in Checkout Page should be configurable.

**Comment by Sanjeewa001** [comment]
_Following Componants are modified to get data via datafiles_
- modified:   components/checkout/BillingDetails.tsx
- modified:   components/checkout/Calender.tsx
- modified:   components/checkout/CheckList.tsx
- modified:   components/checkout/ExtraFacilitation.tsx

**Comment by iamarasekera** [comment]
PR https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/225 is approved.
