### ISSUE TITLE
[Design] Making a terms & conditions link on the register page

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#224]
![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/77c97c8f-b71c-4039-8b83-729c35ea46df)

This should be a Link

**Comment by BupendraDhyan** [comment]
Updated as a link.


![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97863220/50d32c5b-5b2d-4cbf-a5ba-563e5a138ec3)
