### ISSUE TITLE
[Bug]-Login Page

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#226]
1. Lack of Responsiveness on Login Page for Various Devices

Description:
During inspection and responsiveness testing, it was observed that the login page does not adapt appropriately to different devices' screen sizes and resolutions. Specifically, when viewed on devices other than standard desktop screens, such as tablets or smartphones, the layout and elements of the login page fail to adjust properly. This results in a poor user experience and potential usability issues for users accessing the login feature from non-desktop devices.

Steps to Reproduce:

1. Access the login page URL: [(http://localhost:3000/login)] on a desktop computer.
2. Inspect the layout and elements of the login page, ensuring they appear correctly.
3. Utilize browser developer tools to emulate different devices or screen sizes, such as tablets or smartphones.
4. Observe how the login page layout responds to changes in screen size/resolution.
5. Repeat steps 2-4 with various devices and screen sizes to ensure consistency.

Expected Results:

1. The login page should demonstrate responsiveness by adjusting its layout and elements smoothly to fit different screen sizes and resolutions.
2. Text, input fields, buttons, and other components should dynamically adapt to maintain readability and usability across devices.
3. Users should be able to effortlessly interact with all login page elements, regardless of the device being used.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/b6061f91-5dcb-4fd4-a3f5-68cec0b2d8e0)

Actual Results:

1. When viewed on devices with smaller screen sizes, such as tablets or smartphones, the login page layout 
does not adjust appropriately.
2. Elements may appear cramped or stretched, causing readability issues and making it challenging for users to interact with the login page effectively.
3. Certain components may overlap or become inaccessible, leading to a suboptimal user experience on non-desktop devices.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/cb535e4e-e824-4e79-b4d6-dcfff3370bca)

2.Incorrect Font Color Usage in some sections 

Description - The font color is incorrect in some sections.

Test steps -
1.Navigate to the Login page.
2.Verify that the Page is present correctly.

1.
 Title - "Login to Your Account"

Expected result -
Font Color - RGB 17 20 45 100%

Actual result -
Font Color - 0 0 0 87%

2.
Title - "Have an account, Please enter your login details"

Expected result -
Font Color - RGB 81 81 81 100%

Actual result -
Font Color - 0 0 0 87%

3.
Title - "Email", "Password", "Remember Me", "Forgot Password?", "Don’t have an account?"

Expected result -
Font Color - RGB 17 20 45 100%

Actual result -
Font Color - 0 0 0 87%

**Comment by iamarasekera** [comment]
PR https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/230 approved and merged.

**Comment by rmapramodya** [comment]
This is not fixed, Verified in version 1.0.5

**Comment by rmapramodya** [comment]
This is fixed, Verified in version 1.0.5-dup
