### ISSUE TITLE
[Bug]- Register Page

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#228]
1. Title- Incorrect Font Color Usage in some sections

Description - The font color is incorrect in some sections.

Test steps -
1.Navigate to the Register page.
2.Verify that the Page is present correctly.

1.
Title - "Be a Part of Our Journey...."

Expected result -
Font Color - 515151

Actual result -
Font Color - 9A9AB0

2.
Title - "Username

Expected result -
Font Color - 11142D

Actual result -
Font Color - rgb 0 0 0  87%

3.
Title - "I have agree to the rules,"

Expected result -
Font Color - 515151

Actual result -
Font Color - 11142D

2. Title: Space After Footer on Registration Page for Certain Devices

Description:
During inspection of the registration page, it was noticed that on some devices, there is an unexpected space appearing after the footer section. This space disrupts the overall layout and aesthetics of the registration page, potentially causing confusion or misinterpretation for users.

Steps to Reproduce:

1. Access the registration page URL: [http://localhost:3000/register] on various devices.
2. Scroll to the bottom of the registration page.
3. Inspect the area immediately following the footer section.
4. Compare the layout across different devices, including desktops, tablets, and smartphones.

Expected Results:

1. The registration page should display consistently across all devices, with no unexpected spaces or layout issues after the footer.
2. The content of the registration page should seamlessly flow from the footer section without any visible disruptions.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/6abba1c8-0a07-4dd7-9a73-04610aedfb11)

Actual Results:

1. On certain devices, such as [iPad Air, iPad Pro, Surface Pro 7, Asus Zenbook Fold  ], there is a noticeable space appearing after the footer section on the registration page.
2. This space creates a disjointed appearance and may lead users to perceive the page as incomplete or incorrectly loaded.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/bc6d5fda-a89d-4867-a98f-b86c0fe64fc9)

3. Title: Insufficient Spacing Between Header and Topic on Registration Page

Description:
Upon reviewing the developed website, it was observed that there is insufficient spacing between the header and topic sections on the registration page. This lack of spacing negatively impacts the visual hierarchy and readability of the page, requiring adjustments to ensure proper spacing between these elements.

Steps to Reproduce:

1. Visit the registration page of the developed website.
2. Note the proximity between the header and topic sections.
3. Compare the layout on various devices and screen sizes to confirm consistency of the spacing issue.

Expected Results:

1. There should be a sufficient and consistent amount of space between the header and topic sections on the registration page.
2. The spacing should facilitate clear visual separation between these elements, enhancing readability and user experience.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/c1c471ff-ad6e-44e6-be6f-990106284698)

Actual Results:

1. The spacing between the header and topic sections on the registration page is insufficient, resulting in a cramped appearance.
2. This lack of space may diminish the readability and overall aesthetic appeal of the page, potentially causing user frustration.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/499a491a-25e2-43f5-aca8-72dc3abd4e74)

4. Title: "Back to Home" Text Not Linked on Registration Page

Description:
While reviewing the registration page of the developed website, it was noticed that the "Back to Home" text is present, indicating a navigational option for users. However, upon interaction, it was discovered that the text is not linked to redirect users to the homepage as expected. This renders the text ineffective in providing a means for users to return to the homepage, necessitating a fix to ensure proper navigation functionality.

Steps to Reproduce:

1. Navigate to the registration page of the developed website.
2. Locate the "Back to Home" text at the designated location on the page.
3. Attempt to click on the "Back to Home" text to initiate navigation to the homepage.

Expected Results:

1. Clicking on the "Back to Home" text should redirect users to the homepage of the website.

Actual Results:

1.Despite the presence of the "Back to Home" text, clicking on it does not trigger any action, and users are not redirected to the homepage.

**Comment by iamarasekera** [comment]
Assigned to @Sanjeewa001 as @Anjalika11 was not available.
The PR for this fix https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/250 was approved and merged.

**Comment by rmapramodya** [comment]
This is not fixed, Verified in version 1.0.5
