### ISSUE TITLE
[Dev] Develop Card Components section of the blog page

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#257]
Develop the card component section of the blog page and complete the design

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/caaf4e30-b8cb-48a5-a527-735c77562959)

@Sanjeewa001 @BupendraDhyan @rmapramodya please update the design to remove the following section.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/1e52822b-573a-4a28-b558-653a9d3defe3)

**Comment by BupendraDhyan** [comment]
Above section removed and design updated.


![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97863220/12d72d69-e0fa-4a3d-a228-a0dfe48297b2)

**Comment by iamarasekera** [comment]
Send the to qa-1.0.5
