### ISSUE TITLE
[Bug] Build Error Terms & Condition Page :  Element type is invalid: expected a string but got: object.

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#259]
The following build error occurs. You have passed an object where a string is expected. 
![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/b8552f15-3721-42bf-bf76-bcb8c361ae35)

**Comment by iamarasekera** [comment]
Why  have you put [] for a single String? 

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/5c827e0e-2e4a-4f51-8c13-e8da69e3317f)

 content2: [
        "We reserve the right to modify, update, or change these Terms at any time without prior notice. It is your responsibility to review these Terms periodically to stay informed of any updates. Your continued use of our website or services after any changes to the Terms constitutes your acceptance of the revised Terms."
    ]

**Comment by iamarasekera** [comment]
This is fixed in https://github.com/Software-Lifecycle-Consultants/slc-open-hms/commit/22a2b6ce3a93532b358fbd066915521d187f5b68#diff-3d07c41b0854845093a0cac9154d76e04b8710bb7b9cfcf210eaa7d8049631dc

**Comment by Anjalika11** [comment]
Bug fixed Correct the incorrect elements #259

**Comment by rmapramodya** [comment]
This is fixed. Version 1.0.5-dup
