### ISSUE TITLE
[Bug] Build Error in Privacy Policy Page :  Element type is invalid: expected a string but got: object.

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#260]
The following build error occurs. You have passed an object where a string is expected. 

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/513e6582-3fa3-48e4-8b1c-7ca05d7f0fdc)

**Comment by iamarasekera** [comment]
Fixed in the following commits @chithraka99 FYI
https://github.com/Software-Lifecycle-Consultants/slc-open-hms/commit/1dbadff8949155658d61a13e0363c253a322dbd1
https://github.com/Software-Lifecycle-Consultants/slc-open-hms/commit/462e70a2a3bc7db0648e14ce280e2e03719cdd7c

@rmapramodya you can close this as per this comment. 


![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/18adcee0-4373-4805-9aff-fdc8488a86b3)

**Comment by chithraka99** [comment]
Noted.

**Comment by iamarasekera** [comment]
This is fixed in v1.0.2-qa1
