### ISSUE TITLE
[Bug]-Login-Page

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#273]
Title: Space After Footer on login Page for Certain Devices
Description:
During inspection of the login page, it was noticed that on some devices, there is an unexpected space appearing after the footer section. This space disrupts the overall layout and aesthetics of the registration page, potentially causing confusion or misinterpretation for users.

Steps to Reproduce:

Access the registration page URL: [http://localhost:3000/login] on various devices.
Scroll to the bottom of the login page.
Inspect the area immediately following the footer section.
Compare the layout across different devices, including desktops, tablets, and smartphones.

Expected Results:

The login page should display consistently across all devices, with no unexpected spaces or layout issues after the footer.
The content of the login page should seamlessly flow from the footer section without any visible disruptions.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/d2e71503-d9e6-4415-8095-389ba5f2f298)

Actual Results:

On certain devices, such as [iPad Air, iPad Pro, Surface Pro 7, Asus Zenbook Fold ], there is a noticeable space appearing after the footer section on the login page.
This space creates a disjointed appearance and may lead users to perceive the page as incomplete or incorrectly loaded.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/7e499020-98bf-441b-82d8-96a90f2451b7)

**Comment by iamarasekera** [comment]
This issue is fixed in https://github.com/Software-Lifecycle-Consultants/slc-open-hms/commit/4e283ed155e2cf0cdea4a09ab2aed1493cf85f02

@rmapramodya Please verify in 1.0.1-QA6 

This bug is reassigned from @chithraka99 to @iamarasekera  as it was an issue in the main layout.

**Comment by rmapramodya** [comment]
This is fixed, Verified in version QA-v1.0.6
