### ISSUE TITLE
[Bug]-Mobile Responsiveness Issue on 404 Error Page

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#284]
Description:
The error page (the one you see when a page doesn't exist) isn't working well on phones or tablets. When you visit our website on a phone and try to go to a page that doesn't exist, the error page doesn't look right. It's hard to read, and you can't easily go back to the main website.

Test Steps:

Open our website on your phone or tablet.
Try to go to a page that doesn't exist by typing a wrong URL([http://localhost:3000/error-message]).
Look at how the error page appears on your device.

Expected Results:

The error page should look good on your phone or tablet.
Everything on the page should be easy to read and understand.
You should be able to easily go back to the main website.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/c0d90b9a-e92d-421e-924b-f52b4e89109e)

Actual Result:

The error page doesn't fit well on your phone or tablet screen.
Some parts might be hard to see or read.
It's not easy to get back to the main website from the error page.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/f80753c6-38c1-4f05-b236-96b92ecec633)

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/8e1dc8a9-941f-45e4-9fee-45a0dbbe961e)

**Comment by iamarasekera** [comment]
This was fixed by @sinera2000 in https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/305. Please verify in QA6
@rmapramodya  FYI

**Comment by rmapramodya** [comment]
This is not fixed in Version 1.0.2-qa1

this is figma design


![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/dd4d6491-bbd8-459b-ae10-97044ae7c8f9)

this is developed Page


![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/7edba649-6504-4bc6-929e-03e2b4f225a1)


![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/dc8e07fc-da54-426e-8e5b-027705bfa80b)

**Comment by kshkarunarathna** [comment]
This is fixed, Verified in v1.0.2-qa2
