### ISSUE TITLE
[Bug]-Home-Page(Mobile View Overflow Issue on Homepage)

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#288]
Description:
When inspecting the website and simulating mobile view, there's an overflow problem on the homepage. This means content spills out beyond the screen, making it tough to see everything properly.

Test Steps:

1. Open the website on a computer.
2. Right-click on the homepage and choose "Inspect."
3. Switch to mobile view mode.
4. Look at the homepage layout.

Expected Results:

The homepage should fit neatly within the mobile screen, without any content overflow.
It should be easy to see all the content without having to scroll sideways or up and down too much.

Actual Results:

Content spills out beyond the screen edges, making it hard to see everything without scrolling.
This could hide important info and make the site harder to use on mobile devices.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/8a65b214-dd54-430a-b09d-1bd6bb7479e7)

**Comment by iamarasekera** [comment]
Fixed in https://github.com/Software-Lifecycle-Consultants/slc-open-hms/commit/3eb4a5ebb9720e479b47682ac00ef0b9b3d5d390

**Comment by rmapramodya** [comment]
This is fixed, Verified in version 1.0.5
