### ISSUE TITLE
[Bug]-Register page

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#300]
Title: Space After Footer on Registration Page for Certain Devices

Description:
During inspection of the registration page, it was noticed that on some devices, there is an unexpected space appearing after the footer section. This space disrupts the overall layout and aesthetics of the registration page, potentially causing confusion or misinterpretation for users.

Steps to Reproduce:

Access the registration page URL: [http://localhost:3000/register] on various devices.
Scroll to the bottom of the registration page.
Inspect the area immediately following the footer section.
Compare the layout across different devices, including desktops, tablets, and smartphones.
Expected Results:

The registration page should display consistently across all devices, with no unexpected spaces or layout issues after the footer.
The content of the registration page should seamlessly flow from the footer section without any visible disruptions.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/c0cfbb1f-46d0-43f6-9d05-c79b76d30308)

Actual Results:

On certain devices, such as [iPad Air, iPad Pro, Surface Pro 7, Asus Zenbook Fold ], there is a noticeable space appearing after the footer section on the registration page.
This space creates a disjointed appearance and may lead users to perceive the page as incomplete or incorrectly loaded.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/e1070031-1160-4362-8783-ba155f2ae90d)

**Comment by iamarasekera** [comment]
This issue is fixed in https://github.com/Software-Lifecycle-Consultants/slc-open-hms/commit/4e283ed155e2cf0cdea4a09ab2aed1493cf85f02

@rmapramodya Please verify in 1.0.1-QA6

**Comment by rmapramodya** [comment]
This is fixed, Verified in version QA-v1.0.6
