### ISSUE TITLE
[Design] Update Design for Admin Listing page to reflect rooms, meals and services

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#301]
![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/0d5bd3ab-6602-4d16-a291-4e731a6d8365)

Update the Listing Page with 3 sections. So that admin can add items to each section. 
- Rooms
- Meals
- Services

**Comment by BupendraDhyan** [comment]
Designed Admin listing pages.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97863220/148db9ec-9bd6-4870-848a-ab374f1656b7)

**Comment by BupendraDhyan** [comment]
As instructed by Ishara on 5/22/2024, closed this task.
