### ISSUE TITLE
[Bug]-Underlined Links on Login Page

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#303]
Description:
The links at the bottom of the login page (Remember Me, Forgot Password?, Don’t have an account? Register Here., Back to Home) should not have underlines in their design. However, when viewing the website, these links appear underlined, which is not how they were intended to look.

Test Steps:

Go to the login page.
Check the links at the bottom of the page.

Expected Results:
Links should not have underlines in their design.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/094ad152-0e12-475d-a0cb-ee6988e17074)

Actual Results:
Links are underlined on the website, which is not intended.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/9f422681-0168-40b8-ac58-2fc1f4473b0c)

**Comment by Sanjeewa001** [comment]
fixed by @Sanjeewa001 - https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/309

**Comment by rmapramodya** [comment]
This is fixed, Verified in version QA-v1.0.6
