### ISSUE TITLE
[Dev] Admin :  Develop Blog Page UI

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#316]
Develop Blog Page UI as per the deign

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/aabe241c-0995-4176-ae87-71971a7da5ad)

Prototype :  https://www.figma.com/file/B0M4LvASkmA1MCM1v2JFUa/Hotel-Management-System?type=design&node-id=2421-4411&mode=design&t=x09WYMApifmq4qad-0

**Comment by sinera2000** [comment]
The image uploader has not completed yet adding a cover image and adding an author image. So I keep space for it on the page. So frontend for the admin blogpage is partially completed up to now.

**Comment by sinera2000** [comment]
@iamarasekera 
I was not able to find out a solid solution for that the error which is in the BlogForm.tsx file. I do a small work by disabling-next-line react/jsx-key in the error. This is not the actual solution. I will replace asap. After find out a solid solution.



![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/150272147/57e61e26-d978-4dd3-8025-9dd60d9708c0)

**Comment by iamarasekera** [comment]
The PR https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/347 is merged.  @sinera2000 you can check it in v1.02-qa1 and close this dev task

**Comment by iamarasekera** [comment]
The PR https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/358 for updated work is merged
