### ISSUE TITLE
[Bug]-Blog Page-Misalignment in Blog Page Subscription Section

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#326]
Description:
On the blog page, the text "We care about your data in our privacy policy" is not aligned correctly, making it look messy.

Steps to Reproduce:

1. Go to the blog page.
2. Look for the subscription section.
3. Check the alignment of the text "We care about your data in our privacy policy."

Expected Result:
The text "We care about your data in our privacy policy" should be neatly aligned.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/b50cea60-140b-4892-b209-8be166072fe9)

Actual Result:
The text "We care about your data in our privacy policy" is not aligned properly, making it look messy.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/452d476b-de54-4a38-8244-a2c7828300f0)

**Comment by iamarasekera** [comment]
The related PR  https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/333 is approved and merged to release-v1.0.2-qa1

**Comment by rmapramodya** [comment]
This is fixed, Verified in version 1.0.2-qa1
