### ISSUE TITLE
[Dev]-Blog Page-Create Pagination on Blog Page as Shown in Figma

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#328]
Description:
The blog page is missing the pagination feature that's shown in the Figma design. Pagination helps users move between different pages of blog posts, but it's not there on the actual website.

Steps to Reproduce:

1. Go to the blog page on the website.
2. Look for the buttons or links that let you go to the next or previous page of blog posts.
3. Notice that these pagination controls are not there.
4. Compare this with the Figma design, where pagination is included.

Expected Result:
The blog page should have pagination controls, allowing users to easily navigate through different pages of blog posts.

Actual Result:
There are no pagination controls on the blog page, which is different from what's shown in the Figma design.

**Comment by iamarasekera** [comment]
The PR https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/348 is merged. 
@rmapramodya you can verify this in release-v1.0.2-qa1

**Comment by iamarasekera** [comment]
Related PR https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/356 is merged
