### ISSUE TITLE
[Bug]-Blog Detail Page-Incorrect Gap in Blog Detail Page Heading Date Compared to Figma Design

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#329]
Description:
On the blog detail page, the gap between the publication date and the heading doesn't match the design provided in Figma. This inconsistency affects the visual alignment of the content.

Steps to Reproduce:

1. Navigate to a blog detail page.
2. Locate the publication date and the heading of the blog post.
3. Observe the gap between the publication date and the heading.
4. Compare this gap with the design presented in Figma.
5. Note any discrepancies in the alignment and spacing.

Expected Result:
The gap between the publication date and the heading on the blog detail page should match the design provided in Figma, ensuring consistent spacing and alignment.

Actual Result:
The gap between the publication date and the heading on the blog detail page does not match the design from Figma, resulting in an inconsistent layout.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/8db7d7ce-a8cd-4ac9-8162-429323d106e3)

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/d290b7c4-183e-4469-adba-439a625b02fa)

**Comment by iamarasekera** [comment]
The PR https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/333 is merged.

**Comment by rmapramodya** [comment]
This is fixed, Verified in version 1.0.2-qa1
