### ISSUE TITLE
[Bug]-Blog Detail Page- No "View All Posts" Button on Blog Detail Page

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#330]
Description:
When you're reading a specific blog post, there's usually a button called "View All Posts" that helps you get back to the main blog page. But on this website, that button is missing.

Steps to Reproduce:

1. Go to any blog post on the website.
2. Look for a button that says "View All Posts."
3. Notice that there's no such button.
4. Compare this with other websites where you'd typically find this button.

Expected Result:
When reading a blog post, you should see a button called "View All Posts" that takes you back to the main blog page.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/c8d50ece-e2cf-4e42-85fb-35f63aa8805e)

Actual Result:
There's no "View All Posts" button on the blog detail page, making it harder to navigate back to the main blog page.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/5d3f13f5-617e-40b2-8a14-f63f7eac2bcd)

**Comment by iamarasekera** [comment]
The PR https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/333 is merged

**Comment by rmapramodya** [comment]
This is fixed, Verified in version 1.0.2-qa1
