### ISSUE TITLE
[Bug] Contact Us Page - Map Component : Unhandled Runtime Error

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#340]
**Description :**  An error occurs when shifting through the tabs in Nav Bar. 
**Test Steps :**  

1. Go to http://localhost:3000/
2. Click on Nav Bar buttons randomly to move to different pages

 **Expected Results :**  All pages should display the relevant content without any errors
 **Actual Results :** An error : Unhandled Run Time Error (Please refer the attached screenshot ) occurs when move from maps tab to blogs tab/screen 

**Attachments :** 
![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/4ad99e1d-fbbf-44bb-a624-bc8a33c93240)

**Comment by iamarasekera** [comment]
@kshkarunarathna This is fixed in v1.0.2-qa3 
Please verify.

**Comment by kshkarunarathna** [comment]
This is fixed, Verified in release v1.0.2-qa3
