### ISSUE TITLE
[Dev] Update Mobile View in Blog Page

### ISSUE THREAD

**Issue by rmapramodya** [Software-Lifecycle-Consultants/slc-open-hms#352]
Remove the image in Blog Page Mobile view

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/96515463/3bae4ac4-1572-4350-abe3-df57213835f7)

**Comment by iamarasekera** [comment]
The PR https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/356 is merged.
