### ISSUE TITLE
[Dev] Generate PDF for Booking Confirmation

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#361]
1. When a user clicks on Submit Booking Request in Book Now page, a PDF should be generated accordingly the given figma design. 
2. Submit Booking Request should be enabled only when user selects I have agreed to the rules, Terms and Conditions.
3. Email should be generated to the email address input Email Address filed in the Book Now page. 

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/5eb1a22b-efd9-40b3-9de1-a063a0e35089)

Figma Design for PDF
![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/3662ea56-d0c6-43cc-a6eb-7df5e1abd3b4)

**Comment by Sanjeewa001** [comment]
button action on checkbox is done
