### ISSUE TITLE
[Design] Create HTML template for the booking details

### ISSUE THREAD

**Issue by miradagunasekara** [Software-Lifecycle-Consultants/slc-open-hms#39]
Create an HTML template design for the booking details which will be emailed to the hotel owner. It should display all the order information, contact details, product selected, special instructions, services and meals.

**Comment by Chmx00** [comment]
Design Booking Confirmation 

https://www.figma.com/file/B0M4LvASkmA1MCM1v2JFUa/Hotel-Management-System?type=design&node-id=0-1&mode=design&t=IFXeCMeEy8822tSv-0
