### ISSUE TITLE
[Dev]  Implement  success and error message templates

### ISSUE THREAD

**Issue by miradagunasekara** [Software-Lifecycle-Consultants/slc-open-hms#41]
Phase 1 : 
Display the order submission status.
a) Success msg:  Booking request has been sent successfully - We will get back to you with confirmation/ request update after checking availability.
b) Error msg: We seem to be facing a problem while sending your request - Please try again. 

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/fbb09675-af7b-4c07-b2b6-157afaf85e5b)

Phase 2 : 

1.  Create the modal a a reusable component.

2. The image, color, text and button captions should be configurable via a single file.

Figma Prototype  : https://www.figma.com/file/B0M4LvASkmA1MCM1v2JFUa/Hotel-Management-System?type=design&node-id=0-1&mode=design&t=pZZ5gLkScR9XfJc3-0

**Comment by iamarasekera** [comment]
![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/9cad19b9-8cda-4459-ade6-b3e2fe464144)

Requested a change.

**Comment by iamarasekera** [comment]
Approved. https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/70

Does this only contain success message?

**Comment by iamarasekera** [comment]
Requested changes on the PR
https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/180

Since you have done changes to the Banner Component (removal of link to message box ). Please test it in in release-q1.0.4 to ensure nothing is broken.
