### ISSUE TITLE
[QA]  Test Testimonial Component

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#42]
Write your test case here for [these requirements. ](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/issues/44)

**Comment by miradagunasekara** [comment]
Test case ID-1
Description-click profile
Test Steps-
   1. Navigate to the Testimonial section of the page
   2. verify that profile can be clicked and view 
Expected Result- Needs to redirect to profile view section

Test case ID-2
Description-Give Feedback
Test Steps-
   1. Navigate to the Testimonial section 
   2. go for the feedback section in that page
   3. click the feedback section and it needs to have the ability to give the stars and feedback to the users
   4. needs to have text input fields in the feedback section
   5. needs to have the ability to edit the profile picture and the feedback message
Expected Result-need to work all the functionalities properly

Test case ID-3
Description-Read More Button
Test Steps-
    1. Navigate to the Testimonial section of the page
    2. Locate the "Read More" button 
    3. Click the "Read More" button
    4. Verify that the testimonial expands or redirects to a detailed view
    5. Ensure that the expanded view displays additional information beyond the truncated content
Expected Result- The "Read More" button should provide access to the full testimonial content.

**Comment by iamarasekera** [comment]
@miradagunasekara Please update Test case ID-2 - Expected Result to reflect what's in the requirement.

**Comment by iamarasekera** [comment]
Updated changes are reviewed. They are ok.
