### ISSUE TITLE
[Dev] Update the  Home Page :  Footer Section 

### ISSUE THREAD

**Issue by miradagunasekara** [Software-Lifecycle-Consultants/slc-open-hms#43]
Make the following changes to the footer in all pages.

1. Incorporate the following Footer to all pages 

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/82ffd4b9-b6db-42c3-8bc7-4e8fb15065c6)

2.  Rename Destination title to  to Products and the text under it to Product 1, Product 2 and Product 3 respectively.

3. Make sure the following fields in the Footer are linked as below. 

Products
      Products 1 - > Empty page
      Products 2  ->  Empty page
      Products 3 -> Empty page

About 
     Contact Us - > Contact Us page
     Testimonials  ->  Home page
     Ratings -> Home page

Follow Us
    Facebook - > Facebook page  [Should open in a different tab]
    Twitter  ->  Twitter Page [Should open in a different tab]
    Instagram -> Instagram page [Should open in a different tab]

Privacy Policy - > Privacy Policy Page
Terms and Condition -> Terms and Condition Page

4.  Make these values configurable via a single file. 

 [Ref. for Design task](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/issues/31)

 [Figma Prototype](https://www.figma.com/file/B0M4LvASkmA1MCM1v2JFUa/Hotel-Management-System?type=design&node-id=0-1&mode=design&t=aF4YkIQNvw2KCChv-0)

**Comment by Sanjeewa001** [comment]
-  <Link href="/privacy-policy"style={{ color: "white", textDecoration:"none"}}>Privacy Policy</Link>
create links like that for **privacy policy & T'nC** and also create new folders

- <a href="https://web.facebook.com/profile.php?id=100095424093550" target="_blank" style={{ color: "white", textDecoration:"none"}}>{footerContent.socialMediaText3}</a>
create links as above for **social media links**

- create a new folder for product with [...slug]
