### ISSUE TITLE
[Bug] Admin Dashboard - Inadequate Gap Between Graphs and Incorrect Title Placement

### ISSUE THREAD

**Issue by kshkarunarathna** [Software-Lifecycle-Consultants/slc-open-hms#447]
Description:
In the Admin Dashboard, the gap between the two graphs is insufficient, and the title "Customer History" is not positioned at the top of the page above the graphs.

Steps to Reproduce:

1.Log in to the Admin Dashboard.
2.Navigate to the section containing the graphs.
3.Observe the gap between the two graphs.
4,Check the position of the title "Customer History".

Expected Result:

The gap between the two graphs should be sufficient to ensure clear visual separation.
The title "Customer History" should be positioned at the top of the page above the graphs.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97776524/98728a50-5ea2-4877-97c8-cfd66b833050)

Actual Result:

The gap between the two graphs is not enough, causing them to appear cluttered.
The title "Customer History" is not at the top of the page, affecting the layout and readability.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97776524/43da3713-0a15-441d-ab0b-e2aae88abb50)

**Comment by Kasunkule** [comment]
This is fixed in v1.0.2-qa2

**Comment by kshkarunarathna** [comment]
This is not fixed in Version 1.0.2-qa2.  The gap between the two graphs is fixed but the title "Customer History" is not positioned yet at the top of the page above the graphs.

**Comment by iamarasekera** [comment]
@Kasunkule please check and fix as per @kshkarunarathna 's comment above.

**Comment by Kasunkule** [comment]
Fixed the issue according to the Figma design.

**Comment by kshkarunarathna** [comment]
This is fixed, Verified in version 1.0.2-qa3.
