### ISSUE TITLE
[Bug] Admin Room Details Page - Incorrect Label for "Tags" Field in Admin Room Details Page

### ISSUE THREAD

**Issue by kshkarunarathna** [Software-Lifecycle-Consultants/slc-open-hms#449]
Description:
In the Admin Room Details page, the "Tags" field is incorrectly labeled as "Towels". This label needs to be corrected to "Tags".

Steps to Reproduce:

Log in to the Admin Dashboard.
Navigate to the Admin Room Details page.
Locate the field labeled "Towels".
Observe that this field is supposed to be labeled "Tags".

Expected Result:
The field should be labeled "Tags" to correctly represent its purpose.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97776524/a847ca36-69e8-4063-be83-51ded3ce9d87)

Actual Result:
The field is incorrectly labeled as "Towels", which is misleading and incorrect.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97776524/0b510093-338e-4a87-bd88-95e7a28fece3)

**Comment by Kasunkule** [comment]
This is fixed in v1.0.2-qa2

**Comment by kshkarunarathna** [comment]
This is fixed, Verified in v1.0.2-qa2
