### ISSUE TITLE
[Bug] Admin Content Page - Content in the navigation bar is not visible.

### ISSUE THREAD

**Issue by kshkarunarathna** [Software-Lifecycle-Consultants/slc-open-hms#459]
Description:
When clicking on the content in the navigation bar, the user should be navigated to the edit content page. However, the content in the navigation bar cannot be seen.

Steps to Reproduce:

1.Log in to the admin panel.
2.Navigate to the relevant page with the navigation bar.
3.Observe the navigation bar and attempt to find the content.

Expected Result:
The content in the navigation bar should be visible, and clicking on it should navigate the user to the edit content page.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97776524/498d9179-0307-46dd-a02d-0ff85717aea8)

Actual Result:
The content in the navigation bar is not visible, making it impossible to navigate to the edit content page.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97776524/18c93529-23e3-4cc5-8cb2-f881741774fa)

**Comment by Kasunkule** [comment]
Added Content tab into the navbar.

**Comment by kshkarunarathna** [comment]
This is fixed, Verified in version 1.0.2-qa3
