### ISSUE TITLE
[Bug] Admin Settings Icon Navigation Issue

### ISSUE THREAD

**Issue by kshkarunarathna** [Software-Lifecycle-Consultants/slc-open-hms#460]
Description:
Clicking the settings icon in the navigation bar is supposed to navigate the user to the admin settings page. However, it currently redirects the user to the signup page instead.

Steps to Reproduce:

1.Log in to the application.
2.Locate the settings icon in the navigation bar.
3.Click on the settings icon.
4.Observe the Admin Settings Page.

Expected Result:
Clicking the settings icon should navigate the user to the admin settings page.

Actual Result:
Clicking the settings icon redirects the user to the signup page instead of Admin Settings Page.

https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97776524/5e662fd4-988f-498c-a580-bc03d7813803

**Comment by Kasunkule** [comment]
Admin Settings Icon Navigation Issue is fixed

**Comment by kshkarunarathna** [comment]
This is fixed, Verified in version 1.0.2-qa3.

**Comment by kshkarunarathna** [comment]
Reopened as it is only fixed in web not in mobile. Tested version 1.0.2-qa4

**Comment by iamarasekera** [comment]
@kshkarunarathna This is fixed in  v1.0.2-qa4. Please verify and close.

**Comment by kshkarunarathna** [comment]
This is fixed, Verified in v1.0.2-qa4
