### ISSUE TITLE
[Bug] Admin Login Page - Incorrect Redirection to Home Page from "Forgot Password"

### ISSUE THREAD

**Issue by kshkarunarathna** [Software-Lifecycle-Consultants/slc-open-hms#461]
Description:
Clicking on the "Forgot Password" link is intended to redirect users to the password recovery page where they can reset their password. However, it currently redirects users to the home page instead.

Steps to Reproduce:

1.Go to the login page.
2.Locate the "Forgot Password" link on the login form.
3.Click on the "Forgot Password" link.
4.Observe the page you are redirected to.

Expected Result:
Clicking on the "Forgot Password" link should redirect the user to the password recovery page.

Actual Result:
Clicking on the "Forgot Password" link redirects the user to the home page instead of the password recovery page.

https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97776524/448d4e78-72f5-4c18-8e83-4a7c020c321d

**Comment by Kasunkule** [comment]
The redirect to the home page issue is fixed.

**Comment by kshkarunarathna** [comment]
This is fixed, Verified in version 1.0.2-qa3
