### ISSUE TITLE
[Bug] - Explore Page - Room Booking Redirection issue

### ISSUE THREAD

**Issue by kshkarunarathna** [Software-Lifecycle-Consultants/slc-open-hms#499]
Description:
When clicking on the "Book Now" button on the room details page, users are redirected to an error page instead of the Book Now page.

Steps to Reproduce:

1.Navigate to the Explore page.
2.Select any room and click the "Learn More" button.
3.On the room details page, click the "Book Now" button.

Expected Result:
Users should be redirected to the Book Now page where they can select all necessary facilities and fill in the required fields to book the room.

Actual Result:
Users are redirected to an 

https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97776524/01a4b25a-4237-45da-9824-02c178f20d8a

error page instead of the Book Now page.

**Comment by iamarasekera** [comment]
This is fixed in release-v1.0.2-qa3. Please verify and close.
@kshkarunarathna

**Comment by kshkarunarathna** [comment]
This is fixed, Verified in release-v1.0.2-qa3
