### ISSUE TITLE
[Bug] Admin-Content-Components-Entered Text in Text Fields Not Visible

### ISSUE THREAD

**Issue by kshkarunarathna** [Software-Lifecycle-Consultants/slc-open-hms#516]
Description:
When editing content through the admin content components, the entered text in the fields (such as Description and Owner of Copyright) is not visible. This issue is likely due to the font color applied to the text.

Steps to Reproduce:

1.Log in to the admin panel.
2.Navigate to the relevant page with the edit content component.
3.Enter text into the fields (e.g., Description, Owner of Copyright).
4.Observe that the entered text is not visible.

Expected Result:
The entered text in the fields should be visible and readable to the user, allowing for proper content editing.

Actual Result:
The entered text in the fields is not visible, making it difficult or impossible to read or edit the content.

https://github.com/user-attachments/assets/6d716a4b-7ecc-4ac9-aa32-c786ad9fa935

Note:
The same issue has arisen with all other admin panel pages.

**Comment by iamarasekera** [comment]
This is fixed with https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/534 by @wickramasinghe07 
@kshkarunarathna you may verify this in v1.0.2-qa4

**Comment by kshkarunarathna** [comment]
This is fixed, Verified in release v1.0.2-qa4
