### ISSUE TITLE
[BE DEV] Write Service for FAQ section

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#530]
- Admin should be able to input 5 FAQs and 5 answers
- We should be receive the same from FE and display. 

Dependency : dev branch update
@SavindyaA to notify to @chithraka99 to start work.

This dependency has been resolved by @SavindyaA on 16/07/2024

**Comment by chithraka99** [comment]
PR link
https://github.com/Software-Lifecycle-Consultants/hms-net-be/pull/27
