### ISSUE TITLE
[Design] Login Page

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#54]

**Comment by iamarasekera** [comment]
@Bupendra The login page has  to be consistent with the existing design.
I don't think the right hand sigh design (attached) is necessary. 

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/ee543fce-6ac2-4c02-9a08-49951718983c)

Please clone the following project and run it to see the current implementation.
https://github.com/Software-Lifecycle-Consultants/slc-open-hms

**Comment by BupendraDhyan** [comment]
Login page updated.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97863220/fa41ddad-e9fe-4f13-8173-b1a913d01b9e)

**Comment by iamarasekera** [comment]
The design looks ok to me.  As per my feedback today, try to update the text fields with the existing styles used in the other pages.
@BupendraDhyan 

Also get the feedback from @achala87

**Comment by BupendraDhyan** [comment]
Got a feedback from Mr. Achala and update the login page.


![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/97863220/c92afee6-6b92-48b8-9ef7-8714ff1b5cbe)
