### ISSUE TITLE
[Dev] Apply SEO to Home Page and its components

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#545]
Ensure following change are made in the Home Page for better SEO

Meta Tags in Head Component
- [x] Title Tag: Set a unique and descriptive title for each page
- [x] Meta Description: Provide a brief and compelling description of the page's content
- [x] Social media meta tags: Provide a brief and compelling description for social media content (if applicable)
- [ ] Canonical link: Apply rel="canonical" where appropriate to prevent duplicate content issues

Accessibility
- [x] ARIA Labels: Use ARIA attributes for accessibility, on custom components

Link Optimization
- [ ] Internal Links: Use descriptive anchor text for internal links to improve navigation and SEO
- [ ] External Links: Open external links in a new tab

Image Optimization
- [x] Alt Attributes: Always use descriptive alt text for images.

**Comment by BupendraDhyan** [comment]
This is approved by Ishara Amarasekara on 8/7/2024
