### ISSUE TITLE
[Bug] Admin-Rooms-Page & Admin Rooms-Details-Page-Mismatched Button Colors

### ISSUE THREAD

**Issue by kshkarunarathna** [Software-Lifecycle-Consultants/slc-open-hms#547]
Description:
The colors of the "Save" and "Close" buttons on the Admin-Rooms-page and Admin-Rooms-Details page do not match the design specified in the Figma. The discrepancy in button styling affects the visual consistency.

Steps to Reproduce:

1.Log in to the admin panel.
2.Navigate to the Admin-Rooms-page and Admin-Rooms-Details page.
3.Observe the "Save" and "Close" buttons.

Expected Result:
The "Save" and "Close" buttons should have the same colors as specified in the Figma design.

![Image](https://github.com/user-attachments/assets/2ffad27e-fc93-4637-be05-059b42949341)

![Image](https://github.com/user-attachments/assets/97ac8c25-abd8-4d32-a365-fbcdf27f35c2)

Actual Result:
The colors of the "Save" and "Close" buttons differ from the Figma design, causing a mismatch in the interface's visual elements.

![Image](https://github.com/user-attachments/assets/4f5c3c06-4c69-4e0f-92e8-991ca577a4a3)

**Comment by iamarasekera** [comment]
@kshkarunarathna this was fixed by @wickramasinghe07 in v1.0.2-qa5. Please verify.

**Comment by kshkarunarathna** [comment]
This is fixed in the Rooms page only. Please fix in the Rooms-Details page too.
@wickramasinghe07

**Comment by kshkarunarathna** [comment]
This is fixed, Verified in v1.0.2-qa5 release.
