### ISSUE TITLE
[QA] Verify Images Appear on Home Page

### ISSUE THREAD

**Issue by miradagunasekara** [Software-Lifecycle-Consultants/slc-open-hms#57]

**Comment by miradagunasekara** [comment]
Test case ID - 1
Description - Verify All Images Appear on Home Page
Test Steps - 
   1. Launch the web browser.
   2. Navigate to the home page of the website.
   3. Inspect the page to identify all image elements.
   4. Check if the images are displayed correctly without any distortion or missing parts.
 Expected Result - 
All images intended for display on the home page are successfully loaded and appear without any issues.


Test case ID - 2
Description - Verify Image Display in Mobile View on Home Page
Test Steps - 
   1. Open the homepage on a desktop browser.
   2. Resize the browser window to emulate a mobile device screen size.
   3. Identify all the images present on the home page.
   4. Verify that each image is loaded and displayed correctly in the mobile view.
   5. Check the alignment and layout of the images to ensure they fit properly within the smaller screen size.
   6. Confirm that there are no overlapping or excessively large images causing layout issues.
Expected Result - 
All images intended for display on the mobile view of the home page are successfully loaded and appear without any issues.

**Comment by iamarasekera** [comment]
@miradagunasekara 
You have to check if all images in Explore Page also appear.
Also write a test case to check navigations between these 2 pages.

**Comment by iamarasekera** [comment]
Reviewed. Good !
