### ISSUE TITLE
[Dev] Contact Now Banner

### ISSUE THREAD

**Issue by miradagunasekara** [Software-Lifecycle-Consultants/slc-open-hms#59]
1. Create Contact Us Banner  section according to the Figma Design

URL : https://www.figma.com/file/B0M4LvASkmA1MCM1v2JFUa/Hotel-Management-System?type=design&node-id=0-1&mode=design&t=pZZ5gLkScR9XfJc3-0

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/82e59a7d-8368-4a9e-b3ae-afee7d1b2218)

2. When a user click on on Contact Now button user should be navigated to Contact Us page. 

3.  The design should be responsive for mobile, tab and web.

4. All these values (title, description, image, button caption and links) should be configurable via a single file.

**Comment by iamarasekera** [comment]
Requested for changes in PR
https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/62/files#
