### ISSUE TITLE
[Dev] Admin Panel Rooms : Screen Validation

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#609]
As a user managing room details in the admin panel,
I want to ensure that all fields related to room setup are filled out before submitting the form,
so that the room information is complete and accurate.

Acceptance Criteria:
Room Type Field:

1. Given I am on the Admin Panel - Rooms screen,
When I leave the "Room Type" field empty and attempt to save the room details,
Then I should see an error message: "Enter room type".
Beds Field:

2. Given I am on the Admin Panel - Rooms screen,
When I leave the "Beds" field empty and attempt to save the room details,
Then I should see an error message: "Enter beds".
Guests Field:

3. Given I am on the Admin Panel - Rooms screen,
When I leave the "Guests" field empty and attempt to save the room details,
Then I should see an error message: "Enter guests".
Question 01 Field:

4. Given I am on the Admin Panel - Rooms screen,
When I leave the "Question 01" field empty and attempt to save the room details,
Then I should see an error message: "Enter the question".
Question 02 Field:

5. Given I am on the Admin Panel - Rooms screen,
When I leave the "Question 02" field empty and attempt to save the room details,
Then I should see an error message: "Enter the question".
Question 03 Field:

6. Given I am on the Admin Panel - Rooms screen,
When I leave the "Question 03" field empty and attempt to save the room details,
Then I should see an error message: "Enter the question".
Answer 01 Field:

7. Given I am on the Admin Panel - Rooms screen,
When I leave the "Answer 01" field empty and attempt to save the room details,
Then I should see an error message: "Enter the answer".
Answer 02 Field:

8. Given I am on the Admin Panel - Rooms screen,
When I leave the "Answer 02" field empty and attempt to save the room details,
Then I should see an error message: "Enter the answer".
Answer 03 Field:

9. Given I am on the Admin Panel - Rooms screen,
When I leave the "Answer 03" field empty and attempt to save the room details,
Then I should see an error message: "Enter the answer".
Add Service Field:

10. Given I am on the Admin Panel - Rooms screen,
When I leave the "Add Service" field empty and attempt to save the room details,
Then I should see an error message: "Enter services".

**Comment by BupendraDhyan** [comment]
There is a issue in free solo that used in Room type, Guests and Beds. When type and enter in the free solo it will add the value to the list but the typed word is not clearing for enter another one. You have to delete and enter next word.
FYI - @kshkarunarathna
