### ISSUE TITLE
[Dev] Frontend Contact Us Form Validation

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#614]
As a user submitting a query through the Contact Us form,
I want to ensure that all required fields are properly filled and validated,
so that my query is successfully sent without any errors.

Acceptance Criteria:
First Name Field:

1. Given I am on the Contact Us page,
When I leave the "First Name" field empty and click the "Contact Us" button,
Then I should see an error message: "First name is required."
Last Name Field:

2. Given I am on the Contact Us page,
When I leave the "Last Name" field empty and click the "Contact Us" button,
Then I should see an error message: "Last name is required."
Email Address Field:

3. Given I am on the Contact Us page,
When I enter an invalid email address format and click the "Contact Us" button,
Then I should see an error message: "Invalid email address."
Phone Number Field:

4. Given I am on the Contact Us page,
When I enter a phone number that is less than 7 digits or more than 15 digits and click the "Contact Us" button,
Then I should see an error message: "The Telephone Number is not a valid phone number."
Country Field:

5. Given I am on the Contact Us page,
When I do not select a country and click the "Contact Us" button,
Then I should see an error message: "Select your country."
Subject Field:

6. Given I am on the Contact Us page,
When I leave the "Subject" field empty and click the "Contact Us" button,
Then I should see an error message: "Enter the subject."
Message Field:

7. Given I am on the Contact Us page,
When I leave the "Message" field empty and click the "Contact Us" button,
Then I should see an error message: "Message is required."

**Comment by Chmx00** [comment]
![ui issue](https://github.com/user-attachments/assets/4497e66a-2125-40b8-a214-51e7b7fa64ee)

- There is a known issue like, in mobile responsive, the **send message button** goes out of the container.

- -[Issue] Frontend Contact Us Form Validation Of the Mobile responsive
[#626](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/issues/626)
@kshkarunarathna FYI
