### ISSUE TITLE
[Dev] Admin Panel : Destination Cards Validation

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#616]
As an admin managing destination cards,
I want to ensure that all required fields are correctly filled and validated,
so that the content can be saved without errors.

Acceptance Criteria:
Video Title:

1. Given I am on the Destination Cards page,
When I leave the "Video Title" field empty and click the "Save" button,
Then I should see an error message: "Enter the title."
Description (Video):

2. Given I am on the Destination Cards page,
When I leave the "Description" field empty and click the "Save" button,
Then I should see an error message: "Enter the description."
Video URL 1:

3. Given I am on the Destination Cards page,
When I enter an invalid URL or leave the "Video URL 1" field empty and click the "Save" button,
Then I should see an error message: "Invalid URL."
City:

4. Given I am on the Destination Cards page,
When I leave the "City" field empty and click the "Save" button,
Then I should see an error message: "Enter city."
Description (City):

5. Given I am on the Destination Cards page,
When I leave the "Description" field empty and click the "Save" button,
Then I should see an error message: "Enter the description."
Price:

6. Given I am on the Destination Cards page,
When I enter a non-numeric value or leave the "Price" field empty and click the "Save" button,
Then I should see an error message: "Price is required."
Custom Tag 1:

7. Given I am on the Destination Cards page,
When I leave the "Custom Tag 1" field empty and click the "Save" button,
Then I should see an error message: "Enter custom tag."
Custom Tag 2:

8. Given I am on the Destination Cards page,
When I enter a tag longer than 8 characters and click the "Save" button,
Then I should see an error message: "Please enter a tag with 8 characters or less."
Button Name:

9. Given I am on the Destination Cards page,
When I leave the "Button Name" field empty and click the "Save" button,
Then I should see an error message: "Insert button name."

**Comment by BupendraDhyan** [comment]
This is approved and merged by Ishara Amarasekara on 29/08/2024.
