### ISSUE TITLE
[Dev] Admin Panel - Secondary Banner Section Validation

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#619]
As an admin managing the Secondary Banner Section content,
I want to ensure that all required fields in the Secondary Banner Section are correctly filled and validated,
so that the content can be saved without errors.

Acceptance Criteria:
Secondary Banner Section Title:

1.Given I am on the Secondary Banner Section page,
When I leave the "Secondary Banner Section Title" field empty and click the "Save" button,
Then I should see an error message: "Enter the title."
Secondary Banner Section Description:

2. Given I am on the Secondary Banner Section page,
When I leave the "Secondary Banner Section Description" field empty and click the "Save" button,
Then I should see an error message: "Enter the description."
Button Name:

3. Given I am on the Secondary Banner Section page,
When I leave the "Button Name" field empty and click the "Save" button,
Then I should see an error message: "Insert button name."
Video URL:

4. Given I am on the Secondary Banner Section page,
When I enter an invalid URL or leave the "Video URL" field empty and click the "Save" button,
Then I should see an error message: "Enter a valid URL."

**Comment by BupendraDhyan** [comment]
This is approved and merged by Ishara Amarasekara on 29/08/2024.
