### ISSUE TITLE
[Dev] Admin Panel - Blog Content Validation

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#622]
As an admin managing blog content,
I want to ensure that all required fields in the blog section are correctly filled and validated,
so that the blog content can be saved without errors.

Acceptance Criteria:
Title:

1. Given I am on the Blog Content page,
When I leave the "Title" field empty and click the "Save" button,
Then I should see an error message: "Enter the title."
Sub Title:

2. Given I am on the Blog Content page,
When I leave the "Sub Title" field empty and click the "Save" button,
Then I should see an error message: "Enter the sub title."
Tags:

3. Given I am on the Blog Content page,
When I do not add any tags and click the "Save" button,
Then I should see an error message: "Add tags."
Description:

4. Given I am on the Blog Content page,
When I leave the "Description" field empty or it contains less than 5000 characters and click the "Save" button,
Then I should see an error message: "Enter the description."
Cover Image:

5. Given I am on the Blog Content page,
When I do not upload a cover image and click the "Save" button,
Then I should see an error message: "cover image is required."
Author Image:

6. Given I am on the Blog Content page,
When I do not upload an author image and click the "Save" button,
Then I should see an error message: "Upload the author image."
Author Name:

7. Given I am on the Blog Content page,
When I leave the "Author Name" field empty and click the "Save" button,
Then I should see an error message: "Enter author name."
Author Description:

8. Given I am on the Blog Content page,
When I leave the "Author Description" field empty and click the "Save" button,
Then I should see an error message: "Enter the description."
Social Media Links - Twitter:

9. Given I am on the Blog Content page,
When I enter an invalid URL for the Twitter link and click the "Save" button,
Then I should see an error message: "Invalid URL."
Social Media Links - Facebook:

10. Given I am on the Blog Content page,
When I enter an invalid URL for the Facebook link and click the "Save" button,
Then I should see an error message: "Invalid URL."
Social Media Links - LinkedIn:

111. Given I am on the Blog Content page,
When I enter an invalid URL for the LinkedIn link and click the "Save" button,
Then I should see an error message: "Invalid URL."

**Comment by BupendraDhyan** [comment]
This is approved and merged by Ishara Amarasekara on 9/2/2024.
