### ISSUE TITLE
[Bug] Incorrect Font Usage in Footer Sub-components

### ISSUE THREAD

**Issue by miradagunasekara** [Software-Lifecycle-Consultants/slc-open-hms#68]
Bug ID - 1

Description - The font for sub-components in the Product, About, and Follow Us sections of the footer is incorrect. 

Test steps - 
1.Navigate to the bottom of the homepage.
2.Verify that the footer is present on the page.
3.Locate the sub components of Product, About, and Follow Us ("Product 1", "Product 2", "Product 3","Contact us" , "Testimonials", "Rating","Facebook", "Twitter", "Instagram")
4.Inspect the font of the sub components.

Expected result - 
The font for sub components under Product, About, and Follow Us should be "Inter".

Actual result -
The font for sub components under Product, About, and Follow Us is "Montserrat" instead of "Inter".

**Comment by iamarasekera** [comment]
@Chmx00 ensure this issue is also fixed with your Footer Update task.
https://github.com/Software-Lifecycle-Consultants/slc-open-hms/issues/429

**Comment by Chmx00** [comment]
This is fixed in #429

**Comment by iamarasekera** [comment]
@Kasunkule you can verify this bug in  v1.0.2-qa4

**Comment by kshkarunarathna** [comment]
This is fixed, Verified in release v1.0.2-qa4
