### ISSUE TITLE
[Bug] Incorrect Font size and button color usage in Testimonial section

### ISSUE THREAD

**Issue by miradagunasekara** [Software-Lifecycle-Consultants/slc-open-hms#69]
Bug ID - 2 

Description - The font size and the button color of the Read more button in the testimonial section is incorrect. 

Test steps - 
1.Navigate to the homepage.
2.Verify that the testimonial section is present on the page.
3.Locate the "Read more" button
4.Inspect the font size.
5.Inspect the color of it.

Expected result - 
The font size should be 14.
The button color should be rgb(132, 130, 255) / #8482FF

Actual result -
The font size is "15" instead of "14".
The button color is rgb(124, 70, 254) / #7C46FE instead of rgb(132, 130, 255) / #8482FF.

**Comment by Sanjeewa001** [comment]
**[bug Fixed]** all up to date parallel to the figma design ref  PR #170

**Comment by rmapramodya** [comment]
This is fixed, Verified in version 1.0.3
