### ISSUE TITLE
[Dev] Cookie Consent PopUp/ Banner

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#77]
1.  Add a Cookie Consent Banner to Home Page

URL : https://www.figma.com/file/B0M4LvASkmA1MCM1v2JFUa/Hotel-Management-System?type=design&node-id=0-1&mode=design&t=pZZ5gLkScR9XfJc3-0

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/15eb22b6-6989-4c5a-9841-e165a90434e0)

2. When a user click on Reject Button the web site should not save any cookies

3. When a user click on Accept Button the web site should prompt to enter username and save it as a cookie.

4.  The design should be responsive for mobile, tab and web.

5.  All the values should be configurable (Text, Button captions) via a single file.

**Comment by Sanjeewa001** [comment]
cookies done 


![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/87803867/b3867f13-2f30-463e-b71f-559576dfea04)

**Comment by iamarasekera** [comment]
PR needs changes.
https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/131

**Comment by iamarasekera** [comment]
Please document the cookie.tsx

**Comment by iamarasekera** [comment]
https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/166 PR Approved

**Comment by rmapramodya** [comment]
This is fixed, Verified in version 1.0.3
