### ISSUE TITLE
[Bug] The image references are not updated

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#81]
Description : The images references are not updated in Guest Room Details page.

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/9ebddb99-10ed-4935-8cab-f5d4c12ce9fa)

Steps :
1. Go to home page
2. Navigate to Explore Page
3. Select a room and click on the Learn More button

Expected : 
There should be no error messages shown wen navigating to room details page

Actual :
The following error message is prompted when navigated to room details page
![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/d158f71e-a939-44b7-812f-bc2734f00c52)

**Comment by Sanjeewa001** [comment]
**done**

**Comment by iamarasekera** [comment]
https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/82 - Merged

**Comment by rmapramodya** [comment]
This is fixed, Verified in version 1.0.3
