### ISSUE TITLE
[Dev] Update login page design

### ISSUE THREAD

**Issue by miradagunasekara** [Software-Lifecycle-Consultants/slc-open-hms#83]

**Comment by iamarasekera** [comment]
Update the login page UI as per the current Figma design

https://www.figma.com/file/B0M4LvASkmA1MCM1v2JFUa/Hotel-Management-System?type=design&node-id=0-1&mode=design&t=ar6HLm8JAueUpFjK-0

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/76be2991-e980-4612-83b6-12c6c8df9168)

**Comment by iamarasekera** [comment]
Requested changes on the PR
https://github.com/Software-Lifecycle-Consultants/slc-open-hms/pull/177

**Comment by chithraka99** [comment]
Backend Coding yet to be done.
Designed font size was too big, so coded to a relatable size.

**Comment by iamarasekera** [comment]
The button button size is different to the design as the design is is updated at the time of the release.
@chithraka99 you were suppose to mention this as well. 

@rmapramodya  therefore please skip testing font, button size on the UI.
