### ISSUE TITLE
[Bug]  Privacy - Terms and Condition Page includes Elements can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#93]
There are elements in the terms and condition page that  can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`
Please check and fix them. 

Steps to recreate : 
1. Open the project in VS Code and 
2.  Open the Terms and Condition Page

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/69911698-d491-462d-b327-2d7d198bb841)

OR
1.  Build the project using npm run build
2. Check the command prompt 

![Image](https://github.com/Software-Lifecycle-Consultants/slc-open-hms/assets/7510059/d1196cd0-5b84-49e1-929f-6d5698415e4b)

Expected Result :  Project should be compiled without any error
Actual Result :  Project build fail with a compile error

**Comment by iamarasekera** [comment]
This bug no longer in effect as MUI is incorporated to the code.

**Comment by Anjalika11** [comment]
done

**Comment by rmapramodya** [comment]
This is fixed, Verified in version 1.0.3
